---
driver_plugin: ec2
driver_config:
  require_chef_omnibus: latest
  aws_ssh_key_id: <%= ENV['AWS_EC2_KEYPAIR'] %>
#  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>              #autoload from ENV:AWS_ACCESS_KEY
#  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>   #autoload from ENV:AWS_SECRET_ACCESS_KEY

transport:
  ssh_key: <%= ENV['AWS_EC2_KEYPASS'] %>
  username: ec2-user


platforms:
- name: amazon-linux-micro-tokyo
  driver_config:
    instance_type: t1.micro
    image_id: ami-923d12f5 # Amazon Linux AMI 2017.03.0 (HVM), SSD Volume Type
    region: ap-northeast-1
    availability_zone: ap-northeast-1a
    tags:
      Name: test-kitchen-micro
- name: amazon-linux-large-tokyo
  driver_config:
    instance_type: c3.large
    image_id: ami-923d12f5 # Amazon Linux AMI 2017.03.0 (HVM), SSD Volume Type
    region: ap-northeast-1
    availability_zone: ap-northeast-1a
    tags:
      Name: test-kitchen-large

suites:
- name: amimoto
  run_list:
    - recipe[amimoto::default]
    - recipe[amimoto::nginx_default]
    - recipe[amimoto::wordpress]
    - recipe[amimoto::report_handler]
  attributes: {}
- name: hhvm-amimoto
  run_list:
    - recipe[amimoto::default]
    - recipe[amimoto::nginx_default]
    - recipe[amimoto::wordpress]
    - recipe[amimoto::report_handler]
  attributes:
    hhvm:
      enabled: true
#    redis:
#      enabled: true
#    memcached:
#      enabled: false

#- name: amimoto-nfs
#  run_list:
#    - recipe[amimoto::default]
#    - recipe[testmoto::default]
#    - recipe[amimoto::report_handler]
#  attributes: {}

busser:
  sudo: true
